#ifndef _FULL_GROOVE_MODEL_ONNX_H
#define _FULL_GROOVE_MODEL_ONNX_H
/* Auto-generated by bin2c.py */
#include <stddef.h>

#ifdef __cplusplus
extern "C"
{
#endif
    extern const unsigned char full_groove_model_onnx_start[];
    extern const size_t full_groove_model_onnx_size;
#ifdef __cplusplus
}
#endif

#endif
