#ifndef _GROOVE_DECODER_ONNX_H
#define _GROOVE_DECODER_ONNX_H
/* Auto-generated by bin2c.py */
#include <stddef.h>

extern const unsigned char groove_decoder_onnx_start[];
extern const size_t groove_decoder_onnx_size;

#endif
