#ifndef _GROOVE_ENCODER_ONNX_H
#define _GROOVE_ENCODER_ONNX_H
/* Auto-generated by bin2c.py */
#include <stddef.h>

#ifdef __cplusplus
extern "C"
{
#endif
    extern const unsigned char groove_encoder_onnx_start[];
    extern const size_t groove_encoder_onnx_size;
#ifdef __cplusplus
}
#endif

#endif
