#ifndef _SCORE_DECODER_ONNX_H
#define _SCORE_DECODER_ONNX_H
/* Auto-generated by bin2c.py */
#include <stddef.h>

#ifdef __cplusplus
extern "C"
{
#endif

    extern const unsigned char score_decoder_onnx_start[];
    extern const size_t score_decoder_onnx_size;

#ifdef __cplusplus
}
#endif

#endif
