#ifndef _SCORE_ENCODER_ONNX_H
#define _SCORE_ENCODER_ONNX_H
/* Auto-generated by bin2c.py */
#include <stddef.h>

extern const unsigned char score_encoder_onnx_start[];
extern const size_t score_encoder_onnx_size;

#endif
