#ifndef DISTRHO_PLUGIN_INFO_H_INCLUDED
#define DISTRHO_PLUGIN_INFO_H_INCLUDED

#define DISTRHO_PLUGIN_BRAND "WAIVE"
#define DISTRHO_PLUGIN_NAME "WAIVE-Sampler"
#define DISTRHO_PLUGIN_BRAND_ID Waiv
#define DISTRHO_PLUGIN_UNIQUE_ID WaSa
#define DISTRHO_PLUGIN_URI "https://github.com/ThunderboomRecords/WAIVE"
#define DISTRHO_PLUGIN_CLAP_ID "thunderboom.waive.midiinstrument"
#define DISTRHO_PLUGIN_CLAP_FEATURES "instrument", "sampler", "mono"
#define DISTRHO_PLUGIN_VST3_CATEGORIES "Instrument|Sampler"

#define DISTRHO_PLUGIN_HAS_UI 1
#define DISTRHO_UI_USE_NANOVG 1
#define DISTRHO_PLUGIN_IS_RT_SAFE 1
#define DISTRHO_PLUGIN_NUM_INPUTS 0
#define DISTRHO_PLUGIN_NUM_OUTPUTS 2
#define DISTRHO_PLUGIN_WANT_MIDI_INPUT 1
#define DISTRHO_PLUGIN_WANT_MIDI_OUTPUT 0
#define DISTRHO_PLUGIN_WANT_TIMEPOS 1
#define DISTRHO_PLUGIN_WANT_STATE 1
#define DISTRHO_PLUGIN_WANT_FULL_STATE 1
#define DISTRHO_PLUGIN_WANT_DIRECT_ACCESS 1
#define DISTRHO_UI_USER_RESIZABLE 0
#define DISTRHO_UI_FILE_BROWSER 0

#endif
