#ifndef DISTRHO_WAIVE_SEQUENCER_PLUGIN_INFO_H_INCLUDED
#define DISTRHO_WAIVE_SEQUENCER_PLUGIN_INFO_H_INCLUDED

#define DISTRHO_PLUGIN_BRAND "WAIVE"
#define DISTRHO_PLUGIN_NAME "WAIVE-Sequencer"
#define DISTRHO_PLUGIN_BRAND_ID Waiv
#define DISTRHO_PLUGIN_UNIQUE_ID WaSq
#define DISTRHO_PLUGIN_URI "https://github.com/ThunderboomRecords/WAIVE"
#define DISTRHO_PLUGIN_CLAP_ID "waive.midieffect"
#define DISTRHO_PLUGIN_CLAP_FEATURES "note-effect"
#define DISTRHO_PLUGIN_VST3_CATEGORIES "Fx|Generator"

// #define HAVE_OPENGL 1
#define DISTRHO_PLUGIN_HAS_UI 1
#define DISTRHO_UI_USE_NANOVG 1
#define DISTRHO_PLUGIN_IS_RT_SAFE 1
#define DISTRHO_PLUGIN_NUM_INPUTS 2
#define DISTRHO_PLUGIN_NUM_OUTPUTS 2
#define DISTRHO_PLUGIN_WANT_MIDI_INPUT 1
#define DISTRHO_PLUGIN_WANT_MIDI_OUTPUT 1
#define DISTRHO_PLUGIN_WANT_TIMEPOS 1
#define DISTRHO_PLUGIN_WANT_STATE 1
#define DISTRHO_PLUGIN_WANT_FULL_STATE 1
#define DISTRHO_PLUGIN_WANT_DIRECT_ACCESS 1
#define DISTRHO_UI_USER_RESIZABLE 0

#endif
